/**
 * Minimal valid environment variables for Jest and e2e tests.
 */
const testEnv = {
  NODE_ENV: "test",
  PORT: "3000",
  DATABASE_URL:
    "postgresql://rag_kbs:rag_kbs_password@localhost:5432/rag_kbs_test",
  DEFAULT_TENANT_ID: "default",
  REDIS_HOST: "localhost",
  REDIS_PORT: "6379",
  REDIS_PASSWORD: "",
  QDRANT_URL: "http://localhost:6333",
  QDRANT_API_KEY: "",
  QDRANT_COLLECTION: "rag_kbs_test",
  QDRANT_COLLECTION_NAME: "rag_kbs_test",
  QDRANT_VECTOR_SIZE: "1536",
  QDRANT_DISTANCE_METRIC: "Cosine",
  QDRANT_UPSERT_BATCH_SIZE: "64",
  QDRANT_TIMEOUT_MS: "30000",
  STORAGE_DRIVER: "local",
  LOCAL_STORAGE_PATH: "./storage-test",
  S3_ENDPOINT: "",
  S3_REGION: "",
  S3_BUCKET: "",
  S3_ACCESS_KEY_ID: "",
  S3_SECRET_ACCESS_KEY: "",
  S3_FORCE_PATH_STYLE: "false",
  EMBEDDING_PROVIDER: "openai",
  EMBEDDING_MODEL: "text-embedding-3-small",
  EMBEDDING_DIMENSION: "1536",
  EMBEDDING_DISTANCE_METRIC: "Cosine",
  EMBEDDING_BATCH_SIZE: "64",
  EMBEDDING_TIMEOUT_MS: "30000",
  EMBEDDING_MAX_RETRIES: "3",
  EMBEDDING_API_KEY: "test-placeholder",
  OPENAI_API_KEY: "test-placeholder",
  OPENAI_CHAT_MODEL: "gpt-4o-mini",
  CHUNKING_DEFAULT_SIZE: "800",
  CHUNKING_DEFAULT_OVERLAP: "120",
  CHUNKING_TEXT_PREVIEW_LENGTH: "1000",
  CHUNKING_MAX_CHUNKS_PER_DOCUMENT: "10000",
  MAX_UPLOAD_SIZE_MB: "50",
  ALLOWED_UPLOAD_MIME_TYPES:
    "application/pdf,text/plain,text/markdown,application/json,text/csv,text/html,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  INGESTION_QUEUE_NAME: "ingestion",
  INGESTION_CONCURRENCY: "3",
  INGESTION_MAX_ATTEMPTS: "3",
  INGESTION_BACKOFF_DELAY_MS: "5000",
  INGESTION_REMOVE_ON_COMPLETE_COUNT: "1000",
  INGESTION_REMOVE_ON_FAIL_COUNT: "5000",
  INGESTION_JOB_TIMEOUT_MS: "120000",
  INGESTION_MAX_TEXT_CONTENT_BYTES: "1048576",
  INGESTION_TEXT_PREVIEW_LENGTH: "1000",
  BULLMQ_QUEUE_PREFIX: "rag-kbs-test",
  LOG_LEVEL: "error",
  LOG_FORMAT: "json",
  LOG_DIR: "/tmp/rag-kbs-test-logs",
  LOG_ROTATION_ENABLED: "true",
  LOG_RETENTION_DAYS: "14",
  REQUEST_LOGGING_ENABLED: "false",
  REQUEST_BODY_LOGGING_ENABLED: "false",
  WORKER_READY_FILE: "/tmp/rag-kbs-worker.ready",
  SERVICE_NAME: "rag-kbs-api",
  APP_VERSION: "",
  POSTGRES_HEALTH_TIMEOUT_MS: "2000",
  REDIS_HEALTH_TIMEOUT_MS: "2000",
  QDRANT_HEALTH_TIMEOUT_MS: "3000",
  STORAGE_HEALTH_TIMEOUT_MS: "3000",
  QUEUE_HEALTH_TIMEOUT_MS: "2000",
} as const;

for (const [key, value] of Object.entries(testEnv)) {
  if (process.env[key] === undefined) {
    process.env[key] = value;
  }
}
